Style/Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.7.3
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/codebreaker_console/play_state_spec.rb'
    - 'spec/codebreaker_console/game_controller_spec.rb'
